sudo: required

services:
  - docker

before_install:
  - docker pull amarburg/matlab-runtime

script:
  - docker run -v $(pwd):/SCINGE -w /SCINGE --entrypoint "/bin/bash" amarburg/matlab-runtime -c "source install_run_SCINGE.sh; conda list; ls Output/ -l; tests/compare_example_output.sh"
