sudo: required

services:
  - docker

before_install:
  - docker pull amarburg/matlab-runtime

script:
  - docker run -v $(pwd):/SCINGE -w /SCINGE --entrypoint "/bin/bash" amarburg/matlab-runtime -c "./install_run_SCINGE.sh; ls Output/ -l"
