sudo: required

services:
  - docker
  
before_install:
  - docker pull openmicroscopy/octave

script:
  - docker run -v $(pwd):/SCINGE -w /SCINGE --entrypoint bash openmicroscopy/octave -c "octave SCINGE_Example.m; exit 1"
