sudo: required

services:
  - docker

before_install:
  - docker pull agitter/singe:latest

script:
  - docker run -v $(pwd):/SCINGE -w /SCINGE --entrypoint "/bin/bash" agitter/singe:latest -c "docker_test.sh"
