sudo: required

services:
  - docker

before_script:
  - docker pull agitter/singe:tmp
  - docker build --pull --cache-from agitter/singe:tmp -t agitter/singe:tmp -f docker/Dockerfile .

script:
  - docker run -v $(pwd):/SCINGE -w /SCINGE --entrypoint "/bin/bash" agitter/singe:tmp -c "./docker_test.sh"

after_script:
  - docker images
