sudo: required

services:
  - docker
  
before_install:
  - docker pull openmicroscopy/octave

script:
  - docker run -v $(pwd):/SCINGE -w /SCINGE openmicroscopy/octave --entrypoint bash "octave SCINGE_Example.m"
