sudo: required

services:
  - docker

before_install:
  - docker pull amarburg/matlab-runtime

script:
  - docker run -v $(pwd):/SCINGE -w /SCINGE --entrypoint "/bin/bash" amarburg/matlab-runtime -c "ls -l; ls -l /usr/local/MATLAB/MATLAB_Runtime/v94; ./install_run_SCINGE.sh"
