sudo: required

services:
  - docker
  
before_install:
  - docker pull mtmiller/octave-snapshot

script:
  - docker run -v $(pwd):/SCINGE -w /SCINGE --entrypoint "/bin/bash" mtmiller/octave-snapshot -c "octave -v; octave SCINGE_Example.m"
